# --- Including ArcticDEM Samples ---
#
# This tutorial walks you through the steps necessary to sample the ArcticDEM
# at the location of each elevation generated by an `atl06p` request.  The DEM
# value is returned as an additional column in the GeoDataFrame.
#
# The ArcticDEM is a high-resolution digital surface model of the Arctic,
# produced by the Polar Geospatial Center at the University of Minnesota, and
# hosted in a public S3 bucket in the AWS us-west-2 data center. SlideRule is
# able to associate a elevations sampled from the ArcticDEM with each
# elevation generated from ICESat-2's photon cloud data.  The combined dataset
# provides a side-by-side comparison of ATL06-SR elevations with ArcticDEM
# elevations.

# --- Sampling the ArcticDEM mosaic in an `atl06p` request ---
#
# The __"samples"__ parameter is used to request ArcticDEM samples be included
# in `atl06p` responses.  For the ArcticDEM, there are two possible values
# that can be provided: _"arcticdem-mosaic"_ and _"arcticdem-strips"_.

# --- Import and initialize the SlideRule Python package for ICESat-2. ---

from sliderule import sliderule, icesat2
icesat2.init("slideruleearth.io")

# --- Create parameters for a typical `atl06p` processing request. ---

grand_mesa = sliderule.toregion('dicksonfjord.geojson')
parms = {
    "poly": grand_mesa["poly"],
    "t0": "2022-01-01",
    "t1": "2022-06-01",
    "srt": icesat2.SRT_LAND,
    "cnf": icesat2.CNF_SURFACE_HIGH,
    "len": 40.0,
    "res": 20.0
}

# --- Specify sampling the ArcticDEM mosaic. ---

parms["samples"] = {"mosaic": {"asset": "arcticdem-mosaic", "radius": 10.0, "zonal_stats": True}}

# --- Issue the processing request to SlideRule, for only a single granule (to keep the data volume down). ---
#
# When this completes (~10 seconds), the _gdf_ variable should now contain all
# of the results of the elevations calculated by SlideRule with a
# corresponding column for the "arcticdem-mosaic".  Note that the granule
# provided must be in the region of interest.

gdf = icesat2.atl06p(parms, resources=["ATL03_20190314093716_11600203_007_01.h5"])

# --- Display a summary of the results. ---

gdf
